### ISSUE TITLE
Map does not stretch upon page load

### ISSUE THREAD

**Issue by atatchin** [arnaudleclerc/ng-azure-maps#38]
IT does not want to stretch, style is applied.
IT stretches after I resize browser wireframe.
But it should not be this way.
Can you suggest something

azure-map {
    position: absolute;
    height: 100vh;
    width: 100%;
}

![image](https://user-images.githubusercontent.com/14190788/132032204-1b9804ba-301e-4abe-bd38-64bd31a0f3cb.png)

**Comment by arnaudleclerc** [comment]
Hi @atatchin .

I am no css expert, and the library itself does not declare any style as it is the role of your application to display the map and its components according to its need.

As far as I can see, the style is correctly applied on the `azure-map` tag, because I can see some controls on the top right corner. I guess this sidebar where the map is displayed is hidden by default, right ? Probably the canvas takes all the available place when rendered. Maybe loading the map only when the sidebar is displayed could fix your issue ?

In any case, I will close this issue as it not directly linked to this library, but feel free to give me an update on that!
